// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SquareLine_GC9A01_EXT

#include "../ui.h"

void ui_Done_screen_init(void)
{
    ui_Done = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Done, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Done, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Done, LV_DIR_VER);
    lv_obj_set_scroll_snap_y(ui_Done, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_flex_flow(ui_Done, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Done, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Done, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Done, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Done, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDone = lv_obj_create(ui_Done);
    lv_obj_set_width(ui_PanelDone, 240);
    lv_obj_set_height(ui_PanelDone, 240);
    lv_obj_set_x(ui_PanelDone, 76);
    lv_obj_set_y(ui_PanelDone, 113);
    lv_obj_set_align(ui_PanelDone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelDone, LV_OBJ_FLAG_OVERFLOW_VISIBLE | LV_OBJ_FLAG_FLEX_IN_NEW_TRACK |
                    LV_OBJ_FLAG_EVENT_BUBBLE);   /// Flags
    lv_obj_remove_flag(ui_PanelDone, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_PanelDone, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelDone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelDone, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IconDone = lv_image_create(ui_PanelDone);
    lv_image_set_src(ui_IconDone, &ui_img_selected_png);
    lv_obj_set_width(ui_IconDone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IconDone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IconDone, 1);
    lv_obj_set_y(ui_IconDone, -20);
    lv_obj_set_align(ui_IconDone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconDone, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_IconDone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_IconDone, lv_color_hex(0xC3F73A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_IconDone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDone = lv_label_create(ui_PanelDone);
    lv_obj_set_width(ui_LabelDone, 180);   /// 1
    lv_obj_set_height(ui_LabelDone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDone, 0);
    lv_obj_set_y(ui_LabelDone, 62);
    lv_obj_set_align(ui_LabelDone, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDone, _("WarmingDone"));
    lv_obj_set_style_text_color(ui_LabelDone, lv_color_hex(0xC3F73A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelDone, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDone, &ui_font_WIGG_B20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelKeepingProgress = lv_obj_create(ui_Done);
    lv_obj_set_width(ui_PanelKeepingProgress, 240);
    lv_obj_set_height(ui_PanelKeepingProgress, 240);
    lv_obj_set_x(ui_PanelKeepingProgress, 4);
    lv_obj_set_y(ui_PanelKeepingProgress, 1);
    lv_obj_set_align(ui_PanelKeepingProgress, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelKeepingProgress,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_PanelKeepingProgress, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelKeepingProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelKeepingProgress, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IconKeepingProgress = lv_image_create(ui_PanelKeepingProgress);
    lv_image_set_src(ui_IconKeepingProgress, &ui_img_selected_png);
    lv_obj_set_width(ui_IconKeepingProgress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IconKeepingProgress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IconKeepingProgress, 0);
    lv_obj_set_y(ui_IconKeepingProgress, -20);
    lv_obj_set_align(ui_IconKeepingProgress, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconKeepingProgress, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_IconKeepingProgress, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_IconKeepingProgress, lv_color_hex(0xC3F73A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_IconKeepingProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelKeepingProgress = lv_label_create(ui_PanelKeepingProgress);
    lv_obj_set_width(ui_LabelKeepingProgress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelKeepingProgress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelKeepingProgress, 0);
    lv_obj_set_y(ui_LabelKeepingProgress, 77);
    lv_obj_set_align(ui_LabelKeepingProgress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKeepingProgress, _("WarmingDone-KeepingProgress"));
    lv_obj_set_style_text_color(ui_LabelKeepingProgress, lv_color_hex(0xC3F73A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelKeepingProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelKeepingProgress, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelKeepingProgress, &ui_font_WIGG_B20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelChargeProgress = lv_obj_create(ui_Done);
    lv_obj_set_width(ui_PanelChargeProgress, 240);
    lv_obj_set_height(ui_PanelChargeProgress, 240);
    lv_obj_set_x(ui_PanelChargeProgress, 4);
    lv_obj_set_y(ui_PanelChargeProgress, 0);
    lv_obj_set_align(ui_PanelChargeProgress, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelChargeProgress,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_PanelChargeProgress, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelChargeProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelChargeProgress, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChargeArc = lv_arc_create(ui_PanelChargeProgress);
    lv_obj_set_width(ui_ChargeArc, 150);
    lv_obj_set_height(ui_ChargeArc, 150);
    lv_obj_set_x(ui_ChargeArc, 0);
    lv_obj_set_y(ui_ChargeArc, -12);
    lv_obj_set_align(ui_ChargeArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ChargeArc, 50);
    lv_obj_set_style_arc_color(ui_ChargeArc, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ChargeArc, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ChargeArc, lv_color_hex(0xC3F73A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ChargeArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ChargeArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChargeArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelChargeInfo = lv_label_create(ui_PanelChargeProgress);
    lv_obj_set_width(ui_LabelChargeInfo, 160);   /// 1
    lv_obj_set_height(ui_LabelChargeInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelChargeInfo, 0);
    lv_obj_set_y(ui_LabelChargeInfo, 76);
    lv_obj_set_align(ui_LabelChargeInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelChargeInfo, _("BatteryCharging"));
    lv_obj_set_style_text_color(ui_LabelChargeInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelChargeInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelChargeInfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelChargeInfo, &ui_font_WIGG_B20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelChargePercent = lv_label_create(ui_PanelChargeProgress);
    lv_obj_set_width(ui_LabelChargePercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChargePercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelChargePercent, 0);
    lv_obj_set_y(ui_LabelChargePercent, -10);
    lv_obj_set_align(ui_LabelChargePercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelChargePercent, "50");
    lv_obj_set_style_text_color(ui_LabelChargePercent, lv_color_hex(0xC3F73A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelChargePercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelChargePercent, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelChargePercent, &ui_font_Segoe_UI_SB57, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelChargingDone = lv_obj_create(ui_Done);
    lv_obj_set_width(ui_PanelChargingDone, 240);
    lv_obj_set_height(ui_PanelChargingDone, 240);
    lv_obj_set_x(ui_PanelChargingDone, 4);
    lv_obj_set_y(ui_PanelChargingDone, 0);
    lv_obj_set_align(ui_PanelChargingDone, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelChargingDone,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_PanelChargingDone, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelChargingDone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelChargingDone, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IconChargingDone = lv_image_create(ui_PanelChargingDone);
    lv_image_set_src(ui_IconChargingDone, &ui_img_bat_full_png);
    lv_obj_set_width(ui_IconChargingDone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IconChargingDone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IconChargingDone, 3);
    lv_obj_set_y(ui_IconChargingDone, -17);
    lv_obj_set_align(ui_IconChargingDone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconChargingDone, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_IconChargingDone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_IconChargingDone, lv_color_hex(0xC3F73A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_IconChargingDone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelChargingDone = lv_label_create(ui_PanelChargingDone);
    lv_obj_set_width(ui_LabelChargingDone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChargingDone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelChargingDone, 0);
    lv_obj_set_y(ui_LabelChargingDone, 64);
    lv_obj_set_align(ui_LabelChargingDone, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelChargingDone, _("BatteryFull"));
    lv_obj_set_style_text_color(ui_LabelChargingDone, lv_color_hex(0xC3F73A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelChargingDone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelChargingDone, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelChargingDone, &ui_font_WIGG_B20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PanelDone, ui_event_PanelDone, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelKeepingProgress, ui_event_PanelKeepingProgress, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelChargeProgress, ui_event_PanelChargeProgress, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelChargingDone, ui_event_PanelChargingDone, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Done, ui_event_Done, LV_EVENT_ALL, NULL);

}
